version: '3.8'

services:
  # Infrastructure
  postgres:
    image: postgres:15-alpine
    container_name: airline_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airline_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: airline_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: airline_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  # Microservices
  gateway:
    build: ./apps/gateway
    container_name: airline_gateway
    ports:
      - "3000:3000"
    depends_on:
      - flight-service
      - search-service
      - ml-service
    environment:
      - PORT=3000
      - FLIGHT_SERVICE_URL=http://flight-service:3001
      - SEARCH_SERVICE_URL=http://search-service:3002
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
      - ML_SERVICE_URL=http://ml-service:5000

  flight-service:
    build: ./apps/flight-service
    container_name: airline_flight_service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://user:password@postgres:5432/airline_db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672

  search-service:
    build: ./apps/search-service
    container_name: airline_search_service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=3002
      - DATABASE_URL=postgres://user:password@postgres:5432/airline_db
      - REDIS_URL=redis://redis:6379

  notification-service:
    build: ./apps/notification-service
    container_name: airline_notification_service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    environment:
      - PORT=3003
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - GMAIL_USER=denemedila1@gmail.com
      - GMAIL_PASS=ctkm doyb hjnv ijwi

  ml-service:
    build: ./apps/ml-service
    container_name: airline_ml_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  client:
    build: ./apps/client
    container_name: airline_client
    ports:
      - "8080:80"
    depends_on:
      - gateway

volumes:
  pgdata:
